# Config file for MallocWorld
# File name: config.yaml
# By Theo Omnès the 10 oct. 2021

project_name: MallocWorld


# Zones
number_of_zones: 3
zone_1_size: [10, 30]
zone_2_size: [20, 40]
zone_3_size: [30, 50]

zone_1_number_of_monsters: 10
zone_1_number_of_rocks: 3
zone_1_number_of_plants: 10
zone_1_number_of_trees: 10

zone_2_number_of_monsters: 15
zone_2_number_of_rocks: 5
zone_2_number_of_plants: 10
zone_2_number_of_trees: 10

zone_3_number_of_monsters: 20
zone_3_number_of_rocks: 10
zone_3_number_of_plants: 20
zone_3_number_of_trees: 20

# Player
player_start_level: 1
player_start_HP: 100
palyer_start_equipment: [1, 2, 3, 4]
bag_size: 10

# CLI
up_key: z
left_key: q
right_key: d
down_key: s




